FROM php:8.2-fpm
# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# Copy code to directory
COPY . /var/www/isaws/laravel

RUN chown -R www-data:www-data /var/www/isaws/laravel
RUN chmod -R 775 /var/www/isaws/laravel/storage /var/www/isaws/laravel/bootstrap/cache

# # Set working directory
WORKDIR /var/www/isaws/laravel

#RUN composer clear-cache
RUN composer install
# RUN php-fpm
#RUN php artisan key:generate

USER $user

#https://www.digitalocean.com/community/tutorials/how-to-install-and-set-up-laravel-with-docker-compose-on-ubuntu-20-04-pt
#https://www.digitalocean.com/community/tutorials/how-to-set-up-laravel-nginx-and-mysql-with-docker-compose#step-10-migrating-data-and-working-with-the-tinker-console