FROM python:3.10

WORKDIR /var/www/isaws/search-engine

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["python3", "main.py"]
#ENTRYPOINT ["python3"]
#CMD ["main.py"]